T1809E_PROJECT_SEM3/Models/TypeItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace T1809E_PROJECT_SEM3.Models
{
    public class TypeItem
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        [Range(-100, 100)]
        public int Percent { get; set; }
    }
}

T1809E_PROJECT_SEM3/Controllers/TypeItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using T1809E_PROJECT_SEM3.Models;

namespace T1809E_PROJECT_SEM3.Controllers
{
    [Authorize]
    public class TypeItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TypeItems
        public ActionResult Index()
        {
            return View(db.TypeItems.ToList());
        }

        // GET: TypeItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeItem typeItem = db.TypeItems.Find(id);
            if (typeItem == null)
            {
                return HttpNotFound();
            }
            return View(typeItem);
        }

        // GET: TypeItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,Percent")] TypeItem typeItem)
        {
            if (ModelState.IsValid)
            {
                db.TypeItems.Add(typeItem);
                db.SaveChanges();
                TempData["message"] = "Create";
                return RedirectToAction("Index");
            }

            return View(typeItem);
        }

        // GET: TypeItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeItem typeItem = db.TypeItems.Find(id);
            if (typeItem == null)
            {
                return HttpNotFound();
            }
            return View(typeItem);
        }

        // POST: TypeItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Percent")] TypeItem typeItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeItem).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "Edit";
                return RedirectToAction("Index");
            }
            return View(typeItem);
        }

        // GET: TypeItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeItem typeItem = db.TypeItems.Find(id);
            if (typeItem == null)
            {
                return HttpNotFound();
            }
            return View(typeItem);
        }

        // POST: TypeItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TypeItem typeItem = db.TypeItems.Find(id);
            db.TypeItems.Remove(typeItem);
            db.SaveChanges();
            TempData["message"] = "Delete";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

T1809E_PROJECT_SEM3/Views/TypeItems/Create.cshtml
@model T1809E_PROJECT_SEM3.Models.TypeItem

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Type Of Item Manage</h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Create Type Item</strong>
                            </div>
                            <div class="card-body">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                   
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-6">
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-6">
                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-6">
                                                @Html.EditorFor(model => model.Percent, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Percent, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Create" class="btn btn-default" />
                                                <button type="button" class="btn btn-outline-primary">@Html.ActionLink("Back to list", "Index")</button>
                                            </div>
                                        </div>
                                  
                                }

                                
                            </div>

                        </div>


                    </div>

                </section>

            </div>

        </div>
    </div>
</div>











@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

T1809E_PROJECT_SEM3/Views/TypeItems/Delete.cshtml
@model T1809E_PROJECT_SEM3.Models.TypeItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TypeItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Percent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Percent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

T1809E_PROJECT_SEM3/Views/TypeItems/Details.cshtml
@model T1809E_PROJECT_SEM3.Models.TypeItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Type Of Item Manage </h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="card">
                            <div class="card-body">
                                <h4>Type Item </h4>
                                <hr />
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">

                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Name)
                                        </th>

                                        <td>
                                            @Html.DisplayFor(model => model.Name)
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Description)
                                        </th>

                                        <td>
                                            @Html.DisplayFor(model => model.Description)
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Percent)
                                        </th>

                                        <td>
                                            @Html.DisplayFor(model => model.Percent)
                                        </td>
                                    </tr>

                                </table>
                            </div>
                            <p>
                                @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
                                @Html.ActionLink("Back to List", "Index")
                            </p>

                        </div>

                    </div>

                </section>

            </div>
        </div>
    </div>
</div>

T1809E_PROJECT_SEM3/Views/TypeItems/Edit.cshtml
@model T1809E_PROJECT_SEM3.Models.TypeItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Office Manage</h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">

                    <div class="panel-body">
                        <div class="card">
                            <div class="card-body">

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>TypeItem</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.ID)

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Percent, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.Percent, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Percent, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Save" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }

                                <div>
                                    <button type="button" class="btn btn-outline-primary">@Html.ActionLink("Back to list", "Index")</button>
                                </div>

                            </div>

                        </div>

                    </div>

                </section>

            </div>

        </div>
    </div>


</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

T1809E_PROJECT_SEM3/Views/TypeItems/Index.cshtml
@model IEnumerable<T1809E_PROJECT_SEM3.Models.TypeItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}



<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Type Of Item Manage</h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Type Of Item List</strong>
                            </div>
                            <div class="card-body">
                                <p>
                                    @Html.ActionLink("Create New", "Create")
                                </p>
                                <table class="table">
                                    <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Description
                                        </th>
                                        <th>
                                            Percent
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Description)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Percent)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.ID }) |

                                                <button type="button" class="btn btn-sm btn-danger  " data-toggle="modal" data-target="#myModal_@item.ID">
                                                    <i class="fa fa-trash"></i>
                                                </button>


                                                <div class="modal" id="myModal_@item.ID">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">

                                                            <!-- Modal Header -->
                                                            <div class="modal-header">
                                                                <h4 class="modal-title">Message</h4>

                                                            </div>

                                                            <!-- Modal body -->
                                                            <div class="modal-body">
                                                                <span>Are your sure delete</span> <span class="text-uppercase" style="text-decoration: underline; font-weight: bold">@item.Name </span> ?
                                                            </div>

                                                            <!-- Modal footer -->
                                                            <div class="modal-footer">
                                                                <!-- Cỏntroller -->
                                                                @using (Html.BeginForm("Delete", "TypeItems", new { id = item.ID }))
                                                                {
                                                                    @Html.AntiForgeryToken()
                                                                    <input type="submit" value="Delete" class="btn btn-default btn-danger" />
                                                                    <input type="button" class=" btn btn-default " data-dismiss="modal" value="Cancel" />
                                                                }


                                                            </div>

                                                        </div>





                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>

                        </div>


                    </div>

                </section>

            </div>

        </div>
    </div>
</div>
@{ if ((string)TempData["message"] == "Create")
   {
       <script type="text/javascript">
           Swal.fire({
               position: 'top-end',
               icon: 'success',
               title: 'Created',
               showConfirmButton: false,
               timer: 1500
           })
       </script>
   }
   else if ((string)TempData["message"] == "Edit")
   {
       <script type="text/javascript">
           Swal.fire({
               position: 'top-end',
               icon: 'success',
               title: 'Edited',
               showConfirmButton: false,
               timer: 1500
           })
       </script>
   }
   else if ((string)TempData["message"] == "Fail")
   {
       <script type="text/javascript">
           Swal.fire({
               icon: 'error',
               title: 'Oops...',
               text: 'Something went wrong!'
           })
       </script>
   }
   else if ((string)TempData["message"] == "Delete")
   {
       <script type="text/javascript">
           Swal.fire({
               position: 'top-end',
               icon: 'success',
               title: 'Deleted',
               showConfirmButton: false,
               timer: 1500
           })
       </script>
   }
} 