T1809E_PROJECT_SEM3/Models/Office.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace T1809E_PROJECT_SEM3.Models
{
    public class Office
    {
        [Key]
        public string ID { get; set; }
        [Required]
        public string PinCode { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Not a valid email.")]
        public string Email { get; set; }
       
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; }
        [Required]
        public string Address { get; set; }


        public int? District_id { get; set; }
        [ForeignKey("District_id")]
        public virtual District District { get; set; }

        [ForeignKey("Province_id")]
        public virtual Provinces Province { get; set; }
        public int? Province_id { get; set; }

        public StatusEnum Status { get; set; }
        public enum StatusEnum
        {
            Online = 1,
            Offline = 0,
            Delete = 2
        }
    }
}

T1809E_PROJECT_SEM3/Controllers/OfficesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using T1809E_PROJECT_SEM3.Models;

namespace T1809E_PROJECT_SEM3.Controllers
{
    [Authorize]
    public class OfficesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Offices

        public ActionResult Index(string sortOrder,int? province, string searchString, string currentFilter , int? page ,int? status)
        {

            var office = (from l in db.Offices
                          select l);
            ViewBag.CurrentSort = sortOrder;
            if (!status.HasValue)
            {
                office = office.Where(p => (int)p.Status != 2);
            }
            if (status.HasValue)
            {
                ViewBag.Status = status;

                office = office.Where(p => (int)p.Status == status.Value);
            }
            if (province.HasValue)
            {

                office = office.Where(p => (int)p.Province_id == province.Value);
            }
            var listProvince = db.Province.ToList();

            ViewBag.listProvince = new SelectList(listProvince, "id", "_name");

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
           
            if (!string.IsNullOrEmpty(searchString))
            {
                office = office.Where(s => s.Name.Contains(searchString) || s.PinCode.Contains(searchString) || s.Email.Contains(searchString));
            }

            if (string.IsNullOrEmpty(sortOrder) || sortOrder.Equals("status-asc"))

            {
                ViewBag.StatusSort = "status-desc";
                ViewBag.SortIcon = "fa fa-sort-asc";
            }
            else if (sortOrder.Equals("status-desc"))
            {
                ViewBag.StatusSort = "status-asc";
                ViewBag.SortIcon = "fa fa-sort-desc";
            }
            switch (sortOrder)
            {
                case "status-desc":
                    office = office.OrderByDescending(s => s.Status);
                    break;
                case "status-asc":
                    office = office.OrderBy(s => s.Status);
                    break;

                default:
                    office = office.OrderByDescending(s => s.Status);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(office.ToPagedList(pageNumber, pageSize));


        }

        // GET: Offices/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.Offices.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            return View(office);
        }

        // GET: Offices/Create
        public ActionResult Create()
        {
            ViewBag.District_id = new SelectList(db.District, "id", "_name");
            ViewBag.Province_id = new SelectList(db.Province, "id", "_name");
            return View();
        }

        public ActionResult GetDistrict(int? id)
        {
            var listDistrict = db.District.Where(x => x.province_id == id);
            ViewBag.listDistrict = new SelectList(listDistrict, "id", "_name");

            return PartialView("DisplayDistrict");
        }
        // POST: Offices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Office office)
        {
            if (ModelState.IsValid)
            {
                office.ID = "Office" + db.Offices.Count();
                db.Offices.Add(office);
                db.SaveChanges();
                TempData["message"] = "Create";
                return RedirectToAction("Index");
            }
            ViewBag.District_id = new SelectList(db.District, "id", "_name", office.District_id);
            ViewBag.Province_id = new SelectList(db.Province, "id", "_name", office.Province_id);
            return View(office);
        }

        // GET: Offices/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.Offices.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            ViewBag.District_id = new SelectList(db.District, "id", "_name");
            ViewBag.Province_id = new SelectList(db.Province, "id", "_name");
            return View(office);
        }

        // POST: Offices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PinCode,Name,Status,Email,VAT,PhoneNumber,Address,District,Province")] Office office)
        {
            if (ModelState.IsValid)
            {
                db.Entry(office).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.District_id = new SelectList(db.District, "id", "_name", office.District_id);
            ViewBag.Province_id = new SelectList(db.Province, "id", "_name", office.Province_id);
            return View(office);
        }

        // GET: Offices/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Office office = db.Offices.Find(id);
            if (office == null)
            {
                return HttpNotFound();
            }
            office.Status = Office.StatusEnum.Delete;
            db.Entry(office).State = EntityState.Modified;
            db.SaveChanges();
            TempData["message"] = "Delete";
            return RedirectToAction("Index");
        }

        // POST: Offices/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(string id)
        //{
        //    Office office = db.Offices.Find(id);
        //    db.Offices.Remove(office);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

T1809E_PROJECT_SEM3/Views/Offices/Create.cshtml
@model T1809E_PROJECT_SEM3.Models.Office


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Office Manage</h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Create Office</strong>
                            </div>
                            <div class="card-body">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">


                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="row col-lg-12">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.PinCode, htmlAttributes: new { @class = "control-label col-lg-6" })
                                                <div class="col-lg-12">
                                                    @Html.EditorFor(model => model.PinCode, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.PinCode, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-lg-6" })
                                                <div class="col-lg-12">
                                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-4">
                                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-4">
                                                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-12" })
                                            <div class="col-md-4">
                                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="row col-lg-12">
                                            <div class="form-group">
                                                @Html.LabelFor(model => model.Province_id, "Province", htmlAttributes: new { @class = "control-label col-lg-6" })
                                                <div class="col-lg-12">
                                                    @Html.DropDownList("Province_id", ViewBag.ProvinceID as SelectList, "-- Select Province --", htmlAttributes: new { @class = "form-control", @id = "Province_id" })
                                                    @Html.ValidationMessageFor(model => model.Province.id, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                @Html.LabelFor(model => model.District_id, "District", htmlAttributes: new { @class = "control-label col-lg-6" })
                                                <div class="col-lg-12">
                                                    @Html.DropDownList("District_id", new SelectList(" "), "-- Select District  --", htmlAttributes: new { @class = "form-control", @id = "District_id" })
                                                    @Html.ValidationMessageFor(model => model.District_id, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>








                                        <div class="row col-lg-12">

                                            <div class="form-group ">
                                                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-sm-12" })
                                                <div class="col-lg-12">
                                                    @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>



                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <button type="submit" class="btn btn-primary"><span class="ti-plus"></span> Create</button>
                                                <button type="button" class="btn btn-outline-primary">@Html.ActionLink("Back to list", "Index")</button>
                                            </div>
                                        </div>
                                    </div>
                                }
                               


                            </div>

                        </div>


                    </div>

                </section>

            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Province_id").change(function () {
                var provinceID = $(this).val();

                debugger
                $.ajax({
                    type: "post",
                    url: "/Offices/GetDistrict?id=" + provinceID,
                    contentType: "html",
                    success: function (response) {
                        debugger
                        $("#District_id").empty();
                        $("#District_id").append(response);
                    }
                })
            })
        })
    </script>
}

T1809E_PROJECT_SEM3/Views/Offices/DisplayDistrict.cshtml
@model T1809E_PROJECT_SEM3.Models.District

<option value="">-- Select District -- </option>
@if (ViewBag.listDistrict != null)
{
    foreach (var i in ViewBag.listDistrict)
    {
        <option value="@i.Value">@i.Text</option>
    }
}

T1809E_PROJECT_SEM3/Views/Offices/Index.cshtml
@model PagedList.IPagedList<T1809E_PROJECT_SEM3.Models.Office>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared_Admin/_Layout.cshtml";
    var Iconsort = ViewBag.SortIcon;
    <link rel="stylesheet" href="~/AdminTemplate/assets/css/style.css">
    <link rel="stylesheet" href="~/AdminTemplate/assets/css/cs-skin-elastic.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
}
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Office Manage</h1>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="content">
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="card">
                            <div class="card-header">
                                <strong class="card-title">Office List</strong>
                            </div>
                            <div class="card-body">
                                @using (Html.BeginForm("Index", "Offices", FormMethod.Get, new { @name = "search-form" }))
                                {
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <p class="padding">
                                                Search By Keyword
                                            </p>
                                            <div class="input-group">
                                                <button type="submit" class="btn btn-outline-link"> Search <i class="fa fa-search"></i> </button>
                                                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = " Name . . . " })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 .ml-auto">
                                        <p class="padding">
                                            Search By Status
                                        </p>
                                        @Html.DropDownList("status",
                                            EnumHelper.GetSelectList(typeof(T1809E_PROJECT_SEM3.Models.Office.StatusEnum)),
                                            "Select Status",
                                            new { @class = "btn btn-outline-secondary", onchange = "form.submit()" })
                                    </div>
                                    <div class="col-md-4 .ml-auto">
                                        <p class="padding">
                                            Search By Status
                                        </p>
                                        @Html.DropDownList("province",
                                            (IEnumerable<SelectListItem>)ViewBag.listProvince, "Select Provinces",
                                            new { @class = "btn btn-outline-secondary", onchange = "form.submit()" })
                                    </div>
                                </div>
                                }
                                <p class="btn btn-outline-primary">
                                    @Html.ActionLink("Create New +", "Create")
                                </p>
                                @if (Model.Count == 0)
                                {
                                    <div style="font-style:italic ; text-align:center ; font-size: 1.2em;" class="padding">
                                        (NO RESULT IS FOUND)
                                    </div>
                                }
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>
                                                PIN Code
                                            </th>
                                            <th>
                                                Name
                                            </th>
                                            <th>
                                                Email
                                            </th>
                                            <th>
                                                Phone
                                            </th>
                                            <th>
                                                Address
                                            </th>
                                            <th>
                                                District
                                            </th>
                                            <th>
                                                Province
                                            </th>
                                            <th>
                                                @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusSort})
                                                <i class="@Iconsort" aria-hidden="true"></i>
                                            </th>
                                            <th>
                                                Action
                                            </th>
                                        </tr>
                                    <thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.PinCode)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email)
                                                </td>
                                              
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Address)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.District._name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Province._name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Status)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("Edit", "Offices", new { id = item.ID })" class="btn btn-sm btn-light" style="background-color:lightblue"><i class="fa fa-pencil"></i></a> |
                                                    <a href="@Url.Action("Details", "Offices", new { id = item.ID })" class="btn btn-sm btn-light" style="background-color:lightgreen"><i class="fa fa-info-circle"></i></a>  |
                                                    <button type="button" class="btn btn-sm btn-danger  " data-toggle="modal" data-target="#myModal_@item.ID">
                                                        <i class="fa fa-trash"></i>
                                                    </button>


                                                    <div class="modal" id="myModal_@item.ID">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">

                                                                <!-- Modal Header -->
                                                                <div class="modal-header">
                                                                    <h4 class="modal-title">Message</h4>

                                                                </div>

                                                                <!-- Modal body -->
                                                                <div class="modal-body">
                                                                    <span>Are your sure delete</span> <span class="text-uppercase" style="text-decoration: underline; font-weight: bold">@item.Name </span> ?
                                                                </div>

                                                                <!-- Modal footer -->
                                                                <div class="modal-footer">
                                                                    <!-- Cỏntroller -->
                                                                    @using (Html.BeginForm("Delete", "Offices", new { id = item.ID }))
                                                                    {
                                                                        @Html.AntiForgeryToken()
                                                                        <input type="submit" value="Delete" class="btn btn-default btn-danger" />
                                                                        <input type="button" class=" btn btn-default " data-dismiss="modal" value="Cancel" />
                                                                    }


                                                                </div>

                                                            </div>





                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                @if (Model.PageCount > 1)
                                {
                                    <div>
                                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount


                                        @Html.PagedListPager(Model, page => Url.Action("Index",
                                                     new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, status = ViewBag.Status }))

                                    </div>
                                }

                            </div>

                        </div>


                    </div>

                </section>

            </div>

        </div>
    </div>
</div>

<div class="clearfix"></div>
@*@section scrips{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script type="text/javascript">

        $('select[name="status"]').change(function () {
            $('form[name="search-form"]').submit();
        });



    </script>
}*@
@{ if ((string)TempData["message"] == "Create")
    {
        <script type="text/javascript">
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Created',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    }
    else if ((string)TempData["message"] == "Edit")
    {
        <script type="text/javascript">
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Edited',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    }
    else if ((string)TempData["message"] == "Fail")
    {
        <script type="text/javascript">
            Swal.fire({
                icon: 'error',
                title: 'Oops...',
                text: 'Something went wrong!'
            })
        </script>
    }
    else if ((string)TempData["message"] == "Delete")
    {
        <script type="text/javascript">
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Deleted',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
    }
} 